const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),status=document.querySelector('#status');
const W=800,H=600;let scale=1,keys={},touch=null,last=0,score=0,level=1,lives=3,hull=100,shots=[],enemies=[],stars=[];
const plane={x:W/2,y:H-70};for(let i=0;i<90;i++)stars.push({x:Math.random()*W,y:Math.random()*H,z:1+Math.random()*2});
function resize(){const r=canvas.getBoundingClientRect();canvas.width=W;canvas.height=H;scale=r.width/W}resize();addEventListener('resize',resize);addEventListener('keydown',e=>keys[e.key.toLowerCase()]=1);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);touch=point(e)});canvas.addEventListener('pointermove',e=>{if(touch)touch=point(e)});canvas.addEventListener('pointerup',()=>touch=null);
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
function levelUp(){level=Math.min(5,1+Math.floor(score/100));status.textContent=`LEVEL ${level}  |  POWER ${level}`}
function fire(){const spread=level>=5?[-26,-13,0,13,26]:level>=3?[-16,0,16]:[0];spread.forEach(dx=>shots.push({x:plane.x+dx,y:plane.y-24}))}
function reset(){score=0;level=1;lives=3;hull=100;shots=[];enemies=[];plane.x=W/2;plane.y=H-70}
function drawPlane(){const c=level<3?'#49e2ff':level<5?'#ff69be':'#a170ff';ctx.save();ctx.translate(plane.x,plane.y);ctx.shadowBlur=22;ctx.shadowColor=c;ctx.fillStyle='#2467c4';ctx.beginPath();ctx.moveTo(0,-30);ctx.lineTo(-65,18);ctx.lineTo(-18,14);ctx.lineTo(0,30);ctx.lineTo(18,14);ctx.lineTo(65,18);ctx.lineTo(0,-30);ctx.fill();ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(0,-25);ctx.lineTo(-10,28);ctx.lineTo(10,28);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(-6,-5);ctx.lineTo(6,-5);ctx.closePath();ctx.fill();ctx.fillStyle='#ffa452';ctx.fillRect(-12,26,5,11);ctx.fillRect(7,26,5,11);ctx.restore()}
function drawRocket(e){ctx.save();ctx.translate(e.x,e.y);ctx.shadowBlur=18;ctx.shadowColor='#ff5670';ctx.fillStyle='#ff5670';ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(18,8);ctx.lineTo(12,22);ctx.lineTo(-12,22);ctx.lineTo(-18,8);ctx.closePath();ctx.fill();ctx.fillStyle='#ffa452';ctx.beginPath();ctx.moveTo(0,-15);ctx.lineTo(9,2);ctx.lineTo(-9,2);ctx.closePath();ctx.fill();ctx.fillStyle='#ffa452';ctx.beginPath();ctx.moveTo(0,32);ctx.lineTo(-7,18);ctx.lineTo(7,18);ctx.fill();ctx.restore()}
function update(dt){stars.forEach(s=>{s.y+=s.z*dt*.08;if(s.y>H)s.y=0});let speed=level>3?7:6;if(keys.a||keys.arrowleft)plane.x-=speed*dt*.06;if(keys.d||keys.arrowright)plane.x+=speed*dt*.06;if(keys.w||keys.arrowup)plane.y-=speed*dt*.06;if(keys.s||keys.arrowdown)plane.y+=speed*dt*.06;if(touch){plane.x+=(touch.x-plane.x)*.18;plane.y+=(touch.y-plane.y)*.18}plane.x=Math.max(35,Math.min(W-35,plane.x));plane.y=Math.max(45,Math.min(H-45,plane.y));shots.forEach(s=>s.y-=12*dt*.06);shots=shots.filter(s=>s.y>-30);if(!update.cool||performance.now()-update.cool>Math.max(90,220-level*28)){fire();update.cool=performance.now()}if(!update.spawn||performance.now()-update.spawn>Math.max(260,720-level*70)){enemies.push({x:25+Math.random()*(W-50),y:-30,vy:2+Math.random()*2});update.spawn=performance.now()}enemies.forEach(e=>e.y+=e.vy*dt*.06);for(const e of enemies){for(const s of shots){if(Math.abs(e.x-s.x)<22&&Math.abs(e.y-s.y)<25){e.dead=1;s.dead=1;score+=10;levelUp()}}if(Math.abs(e.x-plane.x)<35&&Math.abs(e.y-plane.y)<35){e.dead=1;hull-=25;if(hull<=0){lives--;hull=100;if(!lives){reset()}}}}shots=shots.filter(s=>!s.dead);enemies=enemies.filter(e=>!e.dead&&e.y<H+40)}
function draw(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#060d22');g.addColorStop(1,'#101e3a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);stars.forEach(s=>{ctx.fillStyle='#eaf5ff';ctx.fillRect(s.x,s.y,s.z,s.z)});shots.forEach(s=>{ctx.shadowBlur=16;ctx.shadowColor='#ffe87e';ctx.fillStyle='#ffe87e';ctx.fillRect(s.x-3,s.y-13,6,20)});enemies.forEach(drawRocket);drawPlane();ctx.shadowBlur=0;ctx.fillStyle='#0d1930dd';ctx.fillRect(16,14,300,62);ctx.strokeStyle='#264b7b';ctx.strokeRect(16,14,300,62);ctx.fillStyle='#eaf5ff';ctx.font='20px Rajdhani';ctx.fillText(`SCORE ${String(score).padStart(5,'0')}`,30,39);ctx.fillStyle='#ff69be';ctx.fillText(`LEVEL ${level}  POWER ${level}`,30,63);ctx.fillStyle='#9bb1cf';ctx.fillText(`LIVES ${'x '.repeat(lives)}   HULL ${hull}%`,570,39)}
function loop(t){const dt=Math.min(32,t-last||16);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
